import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  flex: {
    height: 'auto',
    borderRadius: 20,
  },
  container: {
    width: '100%',
    alignItems: 'center',
  },
  product_container: {
    width: '90%',
    height: 'auto',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 2,
    borderRadius: 40,
    marginTop: 30,
  },
  product_image: {
    resizeMode: 'contain',
    width: 550,
    height: 550,
    marginTop: 30,
  },
  product_content: {
    width: '90%',
    padding: 5,
    alignItems: 'center',
    backgroundColor: '#fff',
    marginTop: 20,
    borderRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
  },
  product_name_text: {
    fontSize: 30,
    color: '#021B79',
    //fontWeight: 'bold',
    fontFamily: 'Kanit-SemiBold',
  },
  product_detail_text: {
    fontSize: 22,
    marginTop: 10,
    color: '#8f8f8f',
    fontFamily: 'Kanit-SemiBold',
  },
  product_price_text: {
    fontSize: 30,
    //fontWeight: 'bold',
    color: 'red',
    fontFamily: 'Kanit-SemiBold',
  },
  paymentTitle_content: {
    width: '90%',
    alignItems: 'flex-start',
  },
  payment_title_text: {
    fontSize: 32,
    marginTop: 30,
    // fontWeight: 'bold',
    fontFamily: 'Kanit-Bold',
    textAlign: 'left',
    color: '#021B79',
  },
  product_promotion_content: {
    backgroundColor: '#2B32B2',
    padding: 5,
    width: 100,
    height: 'auto',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
    borderRadius: 50,
    marginBottom: 10,
  },
  product_promotion: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFD700',
    textAlign: 'center',
    marginLeft: 10,
    marginRight: 10,
  },
  btn_payment_content: {
    width: '100%',
    paddingLeft: 120,
    marginTop: 60,
  },
  btn_payment: {
    width: 240,
    height: 240,
    backgroundColor: '#fff',
    margin: 10,
    borderRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
    marginLeft: '0%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cash_image: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
  },
  flatListStyle: {
    margin: 10,
    marginTop: 20,
  },
  btn_cancel_container: {
    width: '40%',
    backgroundColor: 'red',
    borderRadius: 100,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 30,
  },
  btn_cancel_content: {
    borderRadius: 100,
    padding: 12,
  },
  cancel_text: {
    textAlign: 'center',
    color: '#fff',
    // fontWeight: 'bold',
    fontFamily: 'Kanit-SemiBold',
    fontSize: 24,
  },
  w100: {
    width: '100%',
  },
  timer_container: {
    width: '100%',
    alignItems: 'center',
    marginTop: 70,
    bottom: 100,
  },
  timer_content: {
    width: '22%',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#fff',
    padding: 5,
    borderRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
  },
  timer_text: {
    fontSize: 25,
    color: '#FF4B2B',
    fontWeight: 'bold',
  },
  product_image_not_found: {
    resizeMode: 'contain',
    width: 320,
    height: 320,
    backgroundColor: 'transparent',
    tintColor: '#ddd',
  },
  addAmountItemContainer: {
    width: '60%',
    flexDirection: 'row',
    marginTop: 30,
    marginLeft: '20%',
    marginRight: '20%',
  },
  minus_button: {
    width: 70,
    height: 70,
    elevation: 5,
    backgroundColor: '#fff',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input_amount: {
    height: 70,
    width: 200,
    backgroundColor: '#fff',
    elevation: 5,
    borderRadius: 20,
    marginLeft: 20,
    marginRight: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  text_amount: {
    color: '#000',
    fontSize: 30,
    fontWeight: 'bold',
  },
  plus_button: {
    width: 70,
    height: 70,
    elevation: 5,
    backgroundColor: '#fff',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cart_button: {
    width: 170,
    height: 70,
    elevation: 5,
    backgroundColor: '#F5B107',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: '5%',
  },
  product_price_container: {
    width: '100%',
    flexDirection: 'row',
  },
  product_name_content: {
    width: '70%',
    alignItems: 'flex-start',
  },
  product_price_content: {
    width: '30%',
    alignItems: 'flex-end',
  },
  product_detail_content: {
    width: '100%',
    height: 100,
  },
  payment_line: {
    height: 2,
    backgroundColor: '#021B79',
    marginTop: 5,
    width: '100%',
  },
  sumTotal_container: {
    width: '70%',
    padding: 20,
    backgroundColor: '#fff',
    marginTop: 20,
    borderRadius: 10,
    elevation: 5,
    flexDirection: 'row',
  },
  sumTotal_text: {
    fontSize: 22,
    color: '#000',
    fontWeight: 'bold',
    width: '30%',
    textAlign: 'left',
  },
  sumTotal_price: {
    fontSize: 22,
    color: '#000',
    fontWeight: 'bold',
    width: '70%',
    textAlign: 'right',
  },
  add_cart_text: {
    color: '#fff',
    fontSize: 16,
  },
  make_transaction_text: {
    marginTop: '10%',
    fontSize: 22,
    color: '#021B79',
    fontWeight: 'bold',
  },
  timeout_make_transaction: {
    marginTop: '40%',
    fontSize: 16,
    color: '#021B79',
    fontWeight: 'bold',
  },
  coinbill_fail_image: {
    width: 500,
    height: 500,
    resizeMode: 'contain',
  },
  coinbill_fail_text: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 32,
    textAlign: 'center',
  },
  set_center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mt45per: {marginTop: '45%'},
  al_center: {alignItems: 'center'},
});
