import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  body_container: {
    width: '100%',
    alignItems: 'center',
  },
  bg_container: {
    width: 950,
    height: 950,
    resizeMode: 'contain',
    alignItems: 'center',
  },
  container: {
    width: '90%',
    alignItems: 'center',
    marginTop: '3%',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 50,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
    marginBottom: '3%',
  },
  timer_content: {
    width: '35%',
    padding: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timer_title_text: {
    color: '#0F238C',
    fontSize: 30,
    fontFamily: 'Kanit-Regular',
    marginLeft: 10,
  },
  timer_text: {
    color: '#0F238C',
    fontSize: 50,
    fontFamily: 'Kanit-Medium',
  },
  image_payment: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
  },
  title_content: {
    width: '100%',
    alignItems: 'center',
  },
  title_text: {
    color: '#021B79',
    // fontWeight: 'bold',
    fontSize: 30,
    textAlign: 'center',
    fontFamily: 'Kanit-Medium',
    marginBottom: '2%',
  },
  product_price_container: {
    width: '40%',
    flexDirection: 'row',
    marginTop: '5%',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
    padding: 10,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  price_text_content: {
    width: '40%',
    alignItems: 'center',
    left: -40,
    marginTop: 20,
    position: 'absolute',
  },
  prduct_image_content: {
    width: '90%',
    alignItems: 'center',
  },
  prduct_name_text: {
    color: '#000',
    marginTop: 10,
    fontSize: 16,
    textAlign: 'center',
  },
  unit_text_content: {
    width: '35%',
    alignItems: 'flex-end',
  },
  price_text: {
    marginTop: '20%',
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 10,
    backgroundColor: '#0cdfa0',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
  },
  initPrice_text: {
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
  },
  qrcode_container: {
    width: '50%',
    alignItems: 'center',
    marginTop: '1%',
  },
  product_image: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
  },
  mobile_banking_container: {
    width: '70%',
    alignItems: 'center',
  },
  mobile_banking_image: {
    width: 500,
    height: 100,
    resizeMode: 'contain',
  },
  cradit_card_image: {
    width: 300,
    height: 100,
    resizeMode: 'contain',
    marginTop: '2%',
  },
  qrcode_image: {
    width: 340,
    height: 340,
    resizeMode: 'contain',
  },
  btn_cancel_container: {
    width: '50%',
    backgroundColor: 'red',
    borderRadius: 100,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
    marginTop: '3%',
    marginBottom: '2%',
  },
  btn_cancel_content: {
    width: '100%',
    padding: 10,
    borderRadius: 100,
  },
  btn_cancel_text: {
    textAlign: 'center',
    color: '#fff',
    fontSize: 24,
    fontFamily: 'Kanit-Bold',
  },
  success_container: {
    width: '50%',
    borderRadius: 100,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
    marginTop: '2%',
    marginBottom: '2%',
  },
  success_content: {
    width: '100%',
    padding: 10,
    borderRadius: 10,
    borderColor: '#52c234',
    borderWidth: 5,
  },
  success_text: {
    textAlign: 'center',
    color: '#52c234',
    fontWeight: 'bold',
    fontSize: 24,
  },
  error_container: {
    width: '100%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  error_image: {
    width: 400,
    height: 400,
    resizeMode: 'contain',
    marginTop: '40%',
  },
  vending_process_image: {
    width: 300,
    height: 300,
    resizeMode: 'contain',
    top: 80,
  },
  vending_error_image: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
    top: 80,
  },
  down_iamge: {
    width: 100,
    height: 100,
    marginTop: '50%',
    resizeMode: 'contain',
    right: 100,
  },
  vending_process_text: {
    color: '#021B79',
    fontWeight: 'bold',
    fontSize: 24,
    marginTop: '-15%',
  },
  vending_error_text: {
    color: 'red',
    // fontWeight: 'bold',
    fontFamily: 'Kanit-Medium',
    fontSize: 22,
    textAlign: 'center',
    top: 50,
  },
  pickup_container: {
    width: '50%',
    padding: 16,
    borderRadius: 10,
    borderColor: '#FF416C',
    backgroundColor: '#ED213A',
    borderWidth: 3,
    marginTop: 50,
    alignItems: 'center',
  },
  pickup_text: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 26,
    textAlign: 'center',
  },
  icon_pickup: {
    bottom: 13,
    marginRight: 5,
  },
  row: {flexDirection: 'row'},
  footerContainer: {
    width: '100%',
    alignItems: 'center',
  },
  vending_status_container: {
    width: '100%',
    marginTop: 50,
  },
  vending_status_text: {
    fontSize: 18,
    color: '#8f8f8f',
    // fontWeight: 'bold',
    marginLeft: '5%',
    fontFamily: 'Kanit-Medium',
  },
  changeMoney_container: {
    width: '80%',
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  changeMoney_text: {
    fontSize: 26,
    color: '#021B79',
    textAlign: 'center',
    fontFamily: 'Kanit-Medium',
  },
  changeMoney_process_text: {
    fontSize: 20,
    // fontWeight: 'bold',
    color: '#8f8f8f',
    textAlign: 'center',
    fontFamily: 'Kanit-Medium',
  },
  changeMoney_image_container: {
    backgroundColor: '#fff',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
    width: 100,
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginLeft: 20,
    marginTop: -25,
  },
  changeMoney_image_content: {
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
    width: 80,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginTop: 10,
  },
  changeMoney_image: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
  },
  change_color: {color: '#f12711'},
});
