import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  flex: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    width: '60%',
    alignItems: 'center',
    borderRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    padding: 20,
  },
  container2: {
    width: 500,
    alignItems: 'center',
    borderRadius: 60,
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    padding: 20,
  },
  close_container: {
    width: '100%',
    alignItems: 'flex-end',
  },
  title_point_text: {
    marginTop: '8%',
    fontSize: 33,
    fontWeight: 'bold',
    color: '#F37335',
  },
  title_text: {
    fontSize: 33,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  inputBox_container: {
    width: '100%',
    flexDirection: 'row',
  },
  inputBox: {
    width: '85%',
    height: 83,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    backgroundColor: '#fff',
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  btn_clear: {
    width: '100%',
    height: 83,
    padding: 20,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: '#2B32B2',
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  password_text: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#0F2027',
  },
  numpad_container: {
    marginTop: 20,
  },
  btn_numpad: {
    width: '31%',
    margin: '1%',
    height: 140,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    marginRight: '2%',
  },
  zero_container: {
    width: '100%',
    alignItems: 'center',
  },
  btn_numpad_text: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#0F2027',
  },
  btn_clear_text: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
  },
  btn_enter_content: {
    width: '100%',
    height: 80,
    backgroundColor: '#2B32B2',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    marginTop: 20,
  },
  btn_enter_text: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
  },
  star_image_container: {
    width: 190,
    height: 190,
    backgroundColor: '#fff',
    elevation: 10,
    borderRadius: 95,
    position: 'absolute',
    top: -100,
  },
  star_image: {
    width: 190,
    height: 190,
    resizeMode: 'contain',
  },
  bg_success_image: {
    width: 600,
    height: 600,
    resizeMode: 'contain',
    position: 'absolute',
  },
  star_success_image_container: {
    width: 190,
    height: 190,
    backgroundColor: '#fff',
    elevation: 10,
    borderRadius: 95,
    position: 'absolute',
    top: -100,
  },
  star_success_image: {
    width: 190,
    height: 190,
    resizeMode: 'contain',
  },
  congrat_text: {
    color: '#fff',
    fontSize: 33,
    fontWeight: 'bold',
    marginTop: '20%',
  },
  point_text: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
    marginTop: 10,
  },
  discripton_text: {
    color: '#ddd',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 10,
    marginBottom: '10%',
  },
  w100: {width: '100%'},
  w15: {width: '15%'},
  gold_color: {color: '#FDC830'},
});
