const data = {
  startServerData: 0,
  timeServerData: 0,
  temperature: 0,
  pingMS: 0,
  signalLevel: 0,
  KIOSKID: '',
  REGISTERKEY: '',
  TOKEN: '',
  OWNER: '',
  PUBLISH: [],
  SUBSCRIBE: [],
  mqttClient: {},
  topicCheckIn: '',
  topicApiCmd: '',
  topicCron: '',
  decodeToken: {},
  QRPaymentResult: {},
  paymentReady: false,
  VERSION: '3.0.7-C',
  coinStack: {C1: 0, C2: 0, C5: 0, C10: 0},
  startSuccess: false,
  PaymentSuccess: false,
  videoReady: false,
  countMotor: 1,
  testMotor: [],
  blockBill: 1,
};
module.exports = data;
